spring:
  application:
    name: security-security
  datasource:
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/department
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 14C73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327500

app:
  admin:
    username: admin
    password: admin123
    fullname: Администратов Михаил Иванович
    email: admin2000@mail.com

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          web:
            PageableHandlerMethodArgumentResolver: ERROR